### ISSUE TITLE
Example with Media Queries?

### ISSUE THREAD

**Issue by juandc** [kossnocorp/decss#7]

**Comment by kossnocorp** [comment]
@juandc decss, in general, has nothing to do with media queries, you just use that.

You can see many examples of media queries used with decss in wild: https://github.com/kossnocorp/chirrapp/search?l=CSS&q=media&type=Code&utf8=%E2%9C%93

**Comment by kossnocorp** [comment]
Tell me if it's still not clear or you have any other questions ✌️
